version: '3.1'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
#      MONGO_INITDB_ROOT_USERNAME: <admin-user>
#      MONGO_INITDB_ROOT_PASSWORD: kaszanka123
      MONGO_INITDB_DATABASE: inka
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro